version: 0.0

os: windows

files:
  - source: /
  destination: C:\project
hooks:
 
  BeforeInstall:
    - location: scripts\before_install.ps1
    timeout: 300  
    runas: Administrator
  ApplicationStart:
    - location: scripts\application_start.ps1
    timeout: 300
    runas: Administrator
