version: 0.0
os: windows
files:
  - source: /
    destination: /deployed_app
hooks:
  ApplicationStop:
    - location: scripts\stop_app.bat
      timeout: 300
      runas: Administrator 
  BeforeInstall:
    - location: scripts\install_dependencies.bat  
      timeout: 300
      runas: Administrator
  ApplicationStart: 
    - location: scripts\start_app.bat
      timeout: 300 
      runas: Administrator
