version: 0.0
os: linux
files:
  - source: C:\fullstack\projects\react-exprerss-app
    destination: C:\deployed_app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: Administrator
  ApplicationStart: 
    - location: scripts\start_app.bat
      timeout: 300 
      runas: Administrator